=== researcherben/use-case_dependencies/graph_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "use cases": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "short name": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "user stories": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "short name": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "short name",
                    "description"
                  ]
                },
                {
                  "type": "object",
                  "properties": {
                    "short name": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "short name",
                    "description"
                  ]
                }
              ]
            }
          },
          "required": [
            "short name",
            "description",
            "user stories"
          ]
        },
        {
          "type": "object",
          "properties": {
            "short name": {
              "type": "string"
            },
            "user stories": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "short name": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "short name"
                  ]
                }
              ]
            }
          },
          "required": [
            "short name",
            "user stories"
          ]
        }
      ]
    },
    "acceptance tests": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "short name": {
              "type": "string"
            }
          },
          "required": [
            "short name"
          ]
        },
        {
          "type": "object",
          "properties": {
            "short name": {
              "type": "string"
            },
            "status": {
              "type": "string"
            },
            "test status date": {
              "type": "string"
            }
          },
          "required": [
            "short name",
            "status",
            "test status date"
          ]
        }
      ]
    },
    "regression tests": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "short name": {
              "type": "string"
            },
            "status": {
              "type": "string"
            },
            "test status date": {
              "type": "string"
            }
          },
          "required": [
            "short name",
            "status",
            "test status date"
          ]
        }
      ]
    },
    "unit tests": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "short name": {
              "type": "string"
            },
            "status": {
              "type": "string"
            },
            "test status date": {
              "type": "string"
            }
          },
          "required": [
            "short name",
            "status",
            "test status date"
          ]
        }
      ]
    },
    "user-story-to-acceptance": {
      "type": "array",
      "items": [
        {
          "type": "array",
          "items": [
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ]
        },
        {
          "type": "array",
          "items": [
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ]
        }
      ]
    },
    "acceptance-to-regression": {
      "type": "array",
      "items": [
        {
          "type": "array",
          "items": [
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ]
        }
      ]
    },
    "regression-to-unit": {
      "type": "array",
      "items": [
        {
          "type": "array",
          "items": [
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ]
        }
      ]
    }
  },
  "required": [
    "use cases",
    "acceptance tests",
    "regression tests",
    "unit tests",
    "user-story-to-acceptance",
    "acceptance-to-regression",
    "regression-to-unit"
  ]
}

=== researcherben/use-case_dependencies/use_cases_and_user_stories_and_acceptance_tests.json
{
  "use cases": [
    {"short name": "this is fun",
     "description": "minin",
     "user stories": [
       {"short name": "miminin0",
        "description": "some workds"},
       {"short name": "miimmin1",
        "description": "mimimniinn"}
     ]},
    {"short name": "anotehr",
      "user stories": [
         {"short name": "mimiminininin"}
       ]
    }
  ],
  "acceptance tests": [
    {"short name": "asdf"},
    {"short name": "minin",
     "status": "failed",
     "test status date": "2022-04-12"}
  ],
  "regression tests": [
    {"short name": "asdf",
     "status": "passed",
     "test status date": "2022-04-12"}
  ],
  "unit tests": [
    {"short name": "mimin123",
     "status": "passed",
     "test status date": "2022-04-12"}
  ],
  "user-story-to-acceptance": [
    ["miminin0", "asdf"],
    ["miimmin1", "minin"]
  ],
  "acceptance-to-regression": [
    ["asdf", "asdf"]
  ],
  "regression-to-unit": [
    ["asdf", "mimin123"]
  ]

}
